### ISSUE TITLE
Spawns 2 "beam" processes and orphans them

### ISSUE THREAD

**Issue by brainlid** [Psvensso/elixir-docs#2]
## Setup

In the Atom package settings, find "elixir-docs". Separately, open an process monitor (on Linux with Gnome I open System Monitor). Filter the processes to "beam" so it only shows beam processes.
## Steps to Reproduce
- Disable the elixir-docs package. No running beam processes close. 
- Enable the elixir-docs package. 2 new beam processes are launched.
- Disable the elixir-docs package. No running beam processes close. 
- Enable the elixir-docs package. 2 new beam processes are launched.

It creates 2 beam processes at a time and orphans them. When Atom is closed, these processes remain running but are orphaned.

**Comment by Psvensso** [comment]
Ouch, bad one. Thanks for pointing that out @brainlid. 
Please give me a comment back if this fixes the issue on your platform

**Comment by Psvensso** [comment]
Published version 0.1.6 on apm for this.

**Comment by brainlid** [comment]
That fixed it. I'm running on Arch Linux. Thanks!
