### ISSUE TITLE
Does not work on mac os x(?)

### ISSUE THREAD

**Issue by vorce** [Psvensso/elixir-docs#3]
Hi I'm getting some errors when running on Mac OS X. elixir-docs can't find the `iex` executable (need to specify full path?). Then there are some other related problems with erl and mix respectively.

I made a very hackish change to make it work in my fork: https://github.com/vorce/elixir-docs/commit/f7c917e387944b3724780ffc328c632755b6cce7
Didn't want to send a PR for that since it introduced some configuration that is not exposed in an easy to add way. And not sure if it might break something on other platforms...

Cheers!

**Comment by Psvensso** [comment]
Thanks for testing this out for me!
I kinda knew it was a path thing, but dont have access to a Mac atm. 

If you just add a config section,

``` javascript
config: {
    elixirPath:{
      type: 'string',
      default: "",
      description: "Absolute path to elixir executable (required on Mac)"},
    erlangHome:{
      type: 'string',
      default: "",
      description: "Absolute path to erlang bin directory (required on Mac)"}
  },
```

on the exports object (line ~114 in elixir-docs.js) and read the values from there,
just make sure it merges with the latest changes and ill be more than happy to accept your pull request!

**Comment by vorce** [comment]
Ok cool, will try that and send a PR tonight I think. Thanks!

**Comment by acook** [comment]
What about using the [`environment` wrapper](https://github.com/atom-community/environment#environment-)?

**Comment by vorce** [comment]
I tried using that also, no dice

**Comment by keathley** [comment]
would it be possible to get either #4 or #7 merged? Looks like they both have merge conflicts now, but other then that is there anything else that needs to be addressed?
