### ISSUE TITLE
Use --no-start

### ISSUE THREAD

**Issue by mgwidmann** [Psvensso/elixir-docs#5]
Starting up the application will mean the supervision tree will start up as well, which leaves an `iex` process running in the background causing potential side effects that the user is unaware is going on.

Instead, load up the application with `iex -S mix run --no-start`, you'll have access to docs and the supervision tree won't be started up!

**Comment by mgwidmann** [comment]
Took me a while to track this down since first I didn't realize there was a process that was running in the background causing the side effects (data in the DB showing up twice or even when I wasn't running my app), and then after that narrowing it down to which package was causing the problem took some time.

**Comment by Psvensso** [comment]
Want to give me a pull req?

**Comment by mgwidmann** [comment]
It should be just changing [this line](https://github.com/Psvensso/elixir-docs/blob/master/lib/elixir-docs.js#L86) right? I've never done any atom package development personally...

**Comment by Psvensso** [comment]
Yup, just add your params there and restart atom.
